%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Simulation of SINR given different densities of Uniformly Distributed   %
% Base Stations. Shadowing field is generated by R file 5000*5000m area   %
% with de-correlation distance 100m                                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear all;
clc;
%%%%% Initial set up
alpha = 4;
N0 = -104;
lambda_upper = 100; %% Maximal density of a 1000*1000 area
lambda_set = [9 25];
sigma = 8; %% standard deviation of correlated shadow fading
DeCorrDis = 100;
P = 40;


%%%%% load shadowing field
rng('shuffle')

array_id = getenv('PBS_ARRAYID');
if isempty(array_id)
    array_id = '0';
end

field_id = str2num(array_id);

matFileName = sprintf('dat/ShadowField/ExpSF%dDeCorr%d.mat', field_id, DeCorrDis);
if exist(matFileName, 'file')
    load(matFileName);
    shadowField = B;
else
    fprintf('File %s does not exist.\n', matFileName);
end

% load('ExpSF1.mat');
% shadowField = B;
for j = 1:length(lambda_set)
    lambda = lambda_set(j);
    sample_size = 10000; %% 100 BS layout for a particular Shadowing field
    NB_SINR = zeros(sample_size,1);
    NB_SIR = zeros(sample_size,1);
    NB_SINR_Grid = zeros(sample_size,1);
    NB_SIR_Grid = zeros(sample_size,1);
    max_SINR = zeros(sample_size,1);
    max_SIR = zeros(sample_size,1);
    max_SINR_index = zeros(sample_size,1);
    max_SIR_index = zeros(sample_size,1);
    max_SINR_Grid = zeros(sample_size,1);
    max_SIR_Grid = zeros(sample_size,1);
    max_SINR_index_Grid = zeros(sample_size,1);
    max_SIR_index_Grid = zeros(sample_size,1);
    max_power = zeros(sample_size,1);
    max_interference = zeros(sample_size,1);
    max_power_index = zeros(sample_size,1);
    max_interference_index = zeros(sample_size,1);
    r = sqrt(lambda_upper/lambda*1000*1000);
    disp(lambda);
    count = 0;
    sqrtVal = sqrt(lambda);
    Location = GridBaseLayout(r,sqrtVal);
    MU_x = zeros(sample_size,1);
    MU_y = zeros(sample_size,1);
    for n = 1:sample_size
        MU_x(n) = rand * r / sqrtVal - r / 2 /sqrtVal;
        MU_y(n) = rand * r / sqrtVal - r / 2 / sqrtVal;
        dis_Grid = zeros(lambda,1);
        PL_Grid = zeros(lambda,1);
        PL_DB_Grid = zeros(lambda,1);
        for i = 1 : lambda
            dis_Grid(i) = sqrt((MU_x(n)-Location(i,1))^2 + (MU_y(n)-Location(i,2))^2);
            PL_Grid(i) = (dis_Grid(i) + 1)^(-alpha);
            PL_DB_Grid(i) = 10*log10(PL_Grid(i));
            %             Relative_Dis(i,j,:) = [MU_x(i) - Location(j,1) MU_y(i) - Location(j,2)];
        end
        
        %%%%%%%%%%%%%%%%%%%%%%%Rayleigh Fading%%%%%%%%%%%%%%%%%
        %     for j = 1 : n^2
        %         x = sqrt(1/2).*randn(1);
        %         y = sqrt(1/2).*randn(1);
        %         hsquare = x.^2 + y.^2;
        %         Rayleigh(i,j) = hsquare;
        %         Rayleigh_DB(i,j) = 10 * log10(Rayleigh(i,j));
        %     end
        
        %%%%%%%%%%%%%%%%%%%%%Shadow Fading%%%%%%%%%%%%%%%%%%%%%
        shadowing_DB_Grid = zeros(lambda,1);
        shadowing_Grid = zeros(lambda,1);
        for i = 1 : lambda
            if (sqrt(Location(i,1)^2 + Location(i,2)^2) >= 2500)
                shadowing_DB_Grid(i) = normrnd(0, sigma);
            else
                shadowing_DB_Grid(i) = shadowField(round(Location(i,1)) + 2500, round(Location(i,2))+2500) * sigma;
            end
            shadowing_Grid(i) = 10^(shadowing_DB_Grid(i)/10);
        end
        
        
        %%%%%Receive Power
        RxPowerGrid = zeros(lambda, 1);
        for i = 1 : lambda
            %         RxPower(i,j) = 10^(P0/10) * 0.001 * PL(i,j) * Shadowing(i,j) * Rayleigh(i,j);
            RxPowerGrid(i) = 10^(P/10) * 0.001 * PL_Grid(i) * shadowing_Grid(i);
        end
        SINR_Grid = zeros(lambda, 1);
        SIR_Grid = zeros(lambda, 1);
        SINR_DB_Grid = zeros(lambda, 1);
        SIR_DB_Grid = zeros(lambda, 1);
        for i = 1 : lambda
            SINR_Grid(i) = RxPowerGrid(i)/(sum(RxPowerGrid(:))-RxPowerGrid(i)+10^(N0/10));
            SIR_Grid(i) = RxPowerGrid(i)/(sum(RxPowerGrid(:))-RxPowerGrid(i));
            SINR_DB_Grid(i) = 10*log10(SINR_Grid(i));
            SIR_DB_Grid(i) = 10*log10(SIR_Grid(i));
        end
        
        [max_SINR_Grid(n), max_SINR_index_Grid(n)] = max(SINR_DB_Grid);
        [max_SIR_Grid(n), max_SIR_index_Grid(n)] = max(SIR_DB_Grid);
        NB_SINR_Grid(n) = SINR_DB_Grid(floor(lambda/2) + 1);
        NB_SIR_Grid(n) = SIR_DB_Grid(floor(lambda/2) + 1);
        
        BS_points = lambda_upper;
        BS_position_X = rand(lambda_upper,1).*r;
        BS_position_Y = rand(lambda_upper,1).*r;
        BS_position = [BS_position_X-r/2 BS_position_Y-r/2];

        
        MU = [0 0];
        N = size(BS_position);
        dis_BStoMU = zeros(N(1),1);
        %%%%%%%%%%%calculate pathloss
        PL = zeros(N(1),1);
        PL_DB = zeros(N(1),1);
        for i = 1 : N(1)
            dis_BStoMU(i) = sqrt(BS_position(i,1)^2 + BS_position(i,2)^2);
            PL(i) = (dis_BStoMU(i)+1)^(-alpha);
            PL_DB(i) = 10*log10(PL(i));
        end
        [NB_Dis,NB] = min(dis_BStoMU);
        
        %%%%%%%%%%calculate shadow fading%%%%%%%%%%%%%
        shadowing_DB = zeros(N(1),1);
        shadowing = zeros(N(1),1);
        
        for i = 1 : N(1)
            if sqrt(round(BS_position(i,1))^2 + round(BS_position(i,2))^2) >= 2500
                shadowing_DB(i) = normrnd(0, sigma);
            else
                shadowing_DB(i) = B(round(BS_position(i,1))+2500, round(BS_position(i,2))+2500)*sigma;
            end
            shadowing(i) = 10^(shadowing_DB(i)/10);
        end
        
        %%%%%%%%%%calculate Rayleigh fading %%%%%%%%
        rayleigh_DB = zeros(N(1),1);
        rayleigh = zeros(N(1),1);
        for i = 1 : N(1)
            x = sqrt(1/2).*randn(1);
            y = sqrt(1/2).*randn(1);
            rayleigh(i) = x.^2 + y.^2;
            rayleigh_DB(i) = 10*log10(rayleigh(i));
        end
        
        
        RxPower = zeros(N(1),1);
        RxPower_DB = zeros(N(1),1);
        for i = 1 : N(1)
            %             RxPower(i) = 10^(P0/10) * 0.001 * PL(i) * Shadowing(i) * Rayleigh(i);
            RxPower(i) = 10^(P/10) * 0.001 * PL(i) * shadowing(i);
            RxPower_DB = 10*log10(RxPower);
        end
        
        SINR = zeros(N(1),1);
        SIR = zeros(N(1),1);
        SINR_DB = zeros(N(1),1);
        SIR_DB = zeros(N(1),1);
        interference = zeros(N(1),1);
        interference_DB = zeros(N(1),1);
        
        for i = 1 : N(1)
            SINR(i) = RxPower(i)/(sum(RxPower)-RxPower(i)+10^(N0/10));
            SIR(i) = RxPower(i)/(sum(RxPower)-RxPower(i));
            interference(i) = sum(RxPower)-RxPower(i);
            SINR_DB(i) = 10*log10(SINR(i));
            SIR_DB(i) = 10*log10(SIR(i));
            interference_DB(i) = 10*log10(sum(RxPower)-RxPower(i));
        end
        [max_SINR(n), max_SINR_index(n)] = max(SINR_DB);
        [max_SIR(n), max_SIR_index(n)] = max(SIR_DB);
        [max_power(n), max_power_index(n)] = max(RxPower_DB);
        [max_interference(n), max_interference_index(n)] = max(interference_DB);
        NB_SINR(n) = SINR_DB(NB);
        NB_SIR(n) = SIR_DB(NB);
    end
    filename = ['dat/MaxSINR/Max_SINR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'max_SINR');
    filename = ['dat/MaxSIR/Max_SIR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'max_SIR');
    filename = ['dat/NBSINR/Max_SINR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'NB_SINR');
    filename = ['dat/NBSIR/Max_SIR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'NB_SIR');
    filename = ['dat/MaxSINR/Grid_Max_SINR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'max_SINR_Grid');
    filename = ['dat/MaxSIR/Grid_Max_SIR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'max_SIR_Grid');
    filename = ['dat/NBSINR/Grid_Max_SINR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'NB_SINR_Grid');
    filename = ['dat/NBSIR/Grid_Max_SIR_Tx' num2str(P) 'BS' num2str(lambda) 'Exp' num2str(DeCorrDis) 'ID' num2str(field_id) '.mat'];
    save(filename, 'NB_SIR_Grid');
    %     figure(1);
    %     cdfplot(Max_SINR);
    %     hold on;
    %     figure(2);
    %     cdfplot(Max_SIR);
    %     hold on;
    %     Max_SINR(find(Max_SINR >= SINRthreshold)) = 1;
    %     Max_SINR(find(Max_SINR < SINRthreshold)) = 0;
    %     Max_SIR(find(Max_SINR >= SINRthreshold)) = 1;
    %     Max_SIR(find(Max_SINR < SINRthreshold)) = 0;
    %     filename = ['dat/Tx30Max_SINR_Outage_RandomExp100_01' num2str(Lambda) 'ID' num2str(FieldId) '.mat'];
    %     save(filename, 'Max_SINR');
    %     filename = ['dat/Tx30Max_SIR_Outage_RandomExp100_01' num2str(Lambda) 'ID' num2str(FieldId) '.mat'];
    %     save(filename, 'Max_SIR');
    
end
